In [10]:
import sys, os, json, pickle, gzip
sys.path.append('..')
#from src.data import BaseDataset, ConditionalData
import numpy as np
import gzip, pickle
from src.utils import SortedAllElements, Element

In [25]:
with gzip.open('../data/unique_data.pkl.gz','rb') as f:
    unique_data = pickle.load(f)
target_elements = np.zeros(len(SortedAllElements))
for data in unique_data:
    for ele, frac in data['target_comp'].items():
        target_elements[Element(ele).number - 1] += data['count']
target_em = target_elements.astype(bool)

In [32]:
for fn in os.listdir('../src/elmd'):
    if not fn.endswith('json'): continue
    data = json.load(open(f'../src/elmd/{fn}'))
    dtype = []
    dlen = []
    print(fn)
    for ele, feat in data.items():
        try:
            en = Element(ele).number - 1
        except:
            print(ele, feat)
        dtype.append(str(type(feat)))
        if isinstance(feat, (int, float)):
            dlen.append(1)
        else:
            dlen.append(len(feat))
    print(np.unique(dtype, return_counts=True))
    print(np.unique(dlen, return_counts=True))
    print()  
    

elemnet.json
(array(["<class 'list'>"], dtype='<U14'), array([98]))
(array([135]), array([98]))

mod_petti.json
Uue 0
(array(["<class 'int'>"], dtype='<U13'), array([121]))
(array([1]), array([121]))

megnet16.json
Null [-0.044910576194524, 0.004151832312344999, 0.012932863086462002, -0.010163068771362, 0.007605779916048, 0.029269028455017995, 0.033980194479227004, 0.018202271312475, 0.042308006435632005, -0.019319642335176003, -0.035417031496763, 0.020450297743082, -0.016479112207889002, 0.027975413948297, 0.034488748759031004, 0.021560285240411]
(array(["<class 'list'>"], dtype='<U14'), array([95]))
(array([16]), array([95]))

oliynyk.json
(array(["<class 'list'>"], dtype='<U14'), array([85]))
(array([44]), array([85]))

oliynyk_sc.json
(array(["<class 'list'>"], dtype='<U14'), array([85]))
(array([44]), array([85]))

jarvis_sc.json
(array(["<class 'list'>"], dtype='<U14'), array([82]))
(array([438]), array([82]))

random_200.json
(array(["<class 'list'>"], dtype='<U14'), array([82])

In [27]:
dtype

[list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list,
 list]

In [19]:
len(1)

TypeError: object of type 'int' has no len()