In [1]:
import sys, os, json, pickle, gzip, copy
sys.path.append('..')
#from src.data import BaseDataset, ConditionalData
import numpy as np
import gzip, pickle
import matplotlib.pyplot as plt
import matplotlib as mpl
from src.utils import ActiveElements, MetalElements, Element
from src.utils import composit_parser, check_precursor_frequency

# ELMD

In [3]:
with gzip.open('../data/unique_target.pkl.gz','rb') as f:
    unique_target = pickle.load(f)
with gzip.open('../data/unique_precursor.pkl.gz','rb') as f:
    unique_precursor = pickle.load(f)
num_eles = np.zeros((len(ActiveElements), 2))

for data in unique_target:
    for ele, frac in data['target_comp'].items():
        i = ActiveElements.index(ele)
        num_eles[i, 0] += data['count']
for data in unique_precursor:
    for ele, frac in data['precursor_comp'].items():
        i = ActiveElements.index(ele)
        num_eles[i, 1] += len(data['years'])

In [7]:
elmd = {}
for fn in os.listdir('../src/elmd'):
    if not fn.endswith('json'): continue
    elmd[fn.split('.')[0]] = json.load(open(f'../src/elmd/{fn}'))

for fn, data in sorted(elmd.items(), key=lambda x: x[0]):
    dtype = []
    dlen = []
    ele_not_in_table = []
    for ele, feat in data.items():
        dtype.append(str(type(feat)).split()[1].replace('>','').replace('\'',''))
        if isinstance(feat, (int, float)):
            dlen.append(1)
        else:
            dlen.append(len(feat))
        if ele not in ActiveElements:
            ele_not_in_table.append(ele)
    ele_not_in_data = {}
    for i, ele in enumerate(ActiveElements):
        if ele not in data.keys() and num_eles[i].sum() != 0:
            ele_not_in_data[ele] = num_eles[i, :]
    print(fn, dtype[0], dlen[0], len(dtype))
    if len(ele_not_in_data) != 0:
        print(ele_not_in_data)
#    print(ele_not_in_table)
    print()
    

atomic int 1 121

cgcnn list 91 100

elemnet list 135 98

jarvis list 438 82
{'Eu': array([1684., 1685.]), 'Np': array([12., 12.]), 'Pu': array([28., 28.]), 'Am': array([4., 4.]), 'Cm': array([1., 1.])}

jarvis_sc list 438 82
{'Eu': array([1684., 1685.]), 'Np': array([12., 12.]), 'Pu': array([28., 28.]), 'Am': array([4., 4.]), 'Cm': array([1., 1.])}

magpie list 21 97

magpie_sc list 22 97

mat2vec list 199 118

matscholar list 200 103

megnet16 list 16 95
{'Am': array([4., 4.]), 'Cm': array([1., 1.])}

mendeleev int 1 121

mod_petti int 1 121

oliynyk list 44 85
{'Np': array([12., 12.]), 'Pu': array([28., 28.]), 'Am': array([4., 4.]), 'Cm': array([1., 1.])}

oliynyk_sc list 44 85
{'Np': array([12., 12.]), 'Pu': array([28., 28.]), 'Am': array([4., 4.]), 'Cm': array([1., 1.])}

petti int 1 121

random_200 list 200 82
{'Eu': array([1684., 1685.]), 'Np': array([12., 12.]), 'Pu': array([28., 28.]), 'Am': array([4., 4.]), 'Cm': array([1., 1.])}



# Composition featurization functions

In [114]:
with gzip.open('../data/unique_ligand.pkl.gz','rb') as f:
    unique_ligand = pickle.load(f)
with gzip.open('../data/unique_precursor.pkl.gz','rb') as f:
    unique_precursor = pickle.load(f)
with gzip.open('../data/unique_target.pkl.gz','rb') as f:
    unique_target = pickle.load(f)

In [115]:
from src.feature import composition_to_feature

composition_to_feature({'Li':0.2, 'Co':0.2, 'O':0.6}, feature_type='magpie')

array([[6.4000000e+01, 2.2774479e+01, 4.7721799e+02, 1.1600000e+01,
        2.4000001e+00, 9.0400002e+01, 2.6359999e+00, 1.8000000e+00,
        2.4000001e+00, 1.4000000e+00, 0.0000000e+00, 5.5999999e+00,
        2.0000000e-01, 1.2000000e+00, 6.0000002e-01, 0.0000000e+00,
        2.0000000e+00, 1.0830667e+01, 0.0000000e+00, 3.0969423e-01,
        9.1800003e+01]], dtype=float32)

In [15]:
fgs = {}
mask = np.ones(len(unique_precursor), dtype=bool)
for ele in MetalElements:
    precs = []
    for i, prec in enumerate(unique_precursor):
        if ele not in prec['precursor_comp'].keys(): continue
        precs.append([len(prec['years']), prec['precursor_comp']])
        mask[i] = False
    precs = sorted(precs, key=lambda x: x[0], reverse=True)
    precs = sorted(precs, key=lambda x: len(list(x[1].keys())))
    precs = sorted(precs, key=lambda x: tuple(list(x[1].keys())))
    for prec in precs:
        n = np.min(list(prec[1].values()))
        p = '   '.join([f'{e:2s}:{f/n:.2f}' for e, f in prec[1].items()])
        print('{:5d} : {}'.format(prec[0], p))
    if len(prec) != 0:
        print()

precs = []
for j in np.where(mask)[0]:
    prec = unique_precursor[j]
    precs.append([len(prec['years']), prec['precursor_comp']])
            
precs = sorted(precs, key=lambda x: x[0], reverse=True)
precs = sorted(precs, key=lambda x: len(list(x[1].keys())))
precs = sorted(precs, key=lambda x: tuple(list(x[1].keys())))
for prec in precs:
    n = np.min(list(prec[1].values()))
    p = '   '.join([f'{e:2s}:{f/n:.2f}' for e, f in prec[1].items()])
    print('{:5d} : {}'.format(prec[0], p))


   90 : Li:1.00
   22 : Li:1.00   Br:1.00
 3589 : Li:2.00   C :1.00   O :3.00
   57 : Li:1.00   C :1.00   O :3.00
    1 : Li:1.00   C :1.00   O :2.00
   28 : Li:1.00   Cl:1.00
  129 : Li:1.00   F :1.00
   22 : Li:1.00   H :1.00
  124 : Li:1.00   H :3.00   C :2.00   O :2.00
   21 : Li:1.00   H :2.00   N :1.00
  706 : Li:1.00   H :1.00   O :1.00
    1 : Li:1.00   H :2.00   S :1.00   N :1.00   O :3.00
    1 : Li:2.00   H :2.00   S :1.00   O :5.00
    1 : Li:1.00   I :1.00
   24 : Li:3.00   N :1.00
  138 : Li:1.00   N :1.00   O :3.00
  130 : Li:2.00   O :1.00
   26 : Li:1.00   O :1.00
    2 : Li:3.00   P :1.00
    1 : Li:1.00   P :2.33
   78 : Li:1.00   P :1.00   H :2.00   O :4.00
   47 : Li:3.00   P :1.00   O :4.00
    4 : Li:1.67   P :1.00   O :3.33
    4 : Li:1.40   P :1.00   O :3.20
    3 : Li:2.00   P :1.00   O :3.50
    2 : Li:1.00   P :1.00   O :3.00
    1 : Li:3.00   P :1.00   S :4.00
    1 : Li:6.00   P :1.00   S :5.00   Br:1.00
    1 : Li:4.00   P :1.00   Se:2.50   S :2.00
    1

In [18]:
fgs = {}
for prec in unique_precursor:
    n = len(prec['years'])
    metals = {}
    non_metals = {}
    for e, f in prec['precursor_comp'].items():
        if e in MetalElements:
            metals.update({e:f})
        else:
            non_metals.update({e:f})
    k_m = tuple(sorted(list(metals.keys()), key=lambda x: Element(x).number))
    k_fg = tuple(sorted(list(non_metals.keys()), key=lambda x: Element(x).number))
    if k_fg not in fgs.keys():
        fgs[k_fg] = {'count':0, 'metals':{}}
    if k_m not in fgs[k_fg]['metals']:
        fgs[k_fg]['metals'][k_m] = {
            'count':0, 'case':[]
        }
    fgs[k_fg]['count'] += n
    fgs[k_fg]['metals'][k_m]['count'] += n
    fgs[k_fg]['metals'][k_m]['case'].append([prec['precursor_comp'], n])

In [31]:
fgs = {k:v for k,v in sorted(fgs.items(), key=lambda x: len(x[0]))}
fgs = {k:v for k,v in sorted(fgs.items(), key=lambda x: x[0])}
fgs = {k:v for k,v in sorted(fgs.items(), key=lambda x: x[1]['count'])}
for k, v in fgs.items():
    m = list(v['metals'].keys())
    print(k, v['count'], f'{len(m)}/{len(MetalElements)}')
    print(m)
    print()

('C', 'N', 'S') 1 1/87
[()]

('H', 'C', 'N') 1 1/87
[()]

('H', 'C', 'N', 'Br') 1 1/87
[('Pb',)]

('H', 'O', 'Cl') 1 1/87
[('Sr',)]

('H', 'O', 'Se') 1 1/87
[()]

('H', 'S') 1 1/87
[()]

('O', 'F') 1 1/87
[('Tm',)]

('O', 'I') 1 1/87
[('Bi',)]

('O', 'P', 'Cl') 1 1/87
[('Ca',)]

('P', 'S', 'Br') 1 1/87
[('Li',)]

('S', 'Se') 1 1/87
[('Sn',)]

('H', 'C') 2 1/87
[()]

('H', 'C', 'N', 'Cl') 2 2/87
[(), ('Pb',)]

('H', 'C', 'N', 'I') 2 2/87
[(), ('Pb',)]

('H', 'C', 'N', 'O') 2 1/87
[()]

('H', 'C', 'N', 'O', 'P') 2 1/87
[('Fe',)]

('H', 'F') 2 1/87
[('Si',)]

('C', 'S') 3 2/87
[('Nb',), ('W',)]

('H', 'C', 'N', 'S') 3 1/87
[()]

('H', 'Cl') 3 2/87
[(), ('Au',)]

('N', 'P') 3 1/87
[()]

('O', 'F', 'P') 3 1/87
[('Na',)]

('P', 'S', 'Se') 3 2/87
[('Li',), ('Mg',)]

('H', 'C', 'S', 'Br') 4 1/87
[()]

('H', 'C', 'S', 'Cl') 4 1/87
[()]

('O', 'Br') 5 2/87
[('Pb',), ('Bi',)]

('H', 'C', 'S', 'I') 6 1/87
[()]

('H', 'N', 'Br') 6 1/87
[()]

('H', 'O', 'S') 14 3/87
[(), ('Ca',), ('Li',)]

('C', 'N'

# Dataset test

In [1]:
import sys
sys.path.append('..')
import numpy as np
import torch, os
from src.data import ConditionDataset
from src.networks import DNNCVAE
from src.trainer import VAETrainer
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.tensorboard import SummaryWriter

DS = ConditionDataset(target_feat_type='cgcnn')
DS.from_file()

In [2]:
years = np.array([d.year for d in DS])
DS.to('cuda')
train_idx = np.where(years < 2017)[0]
valid_idx = np.where((years > 2016) & (years < 2019))[0]
test_idx = np.where(years > 2018)[0]

train_dl = DataLoader(DS, batch_size=256, sampler=SubsetRandomSampler(train_idx), collate_fn=DS.cfn)
valid_dl = DataLoader(DS, batch_size=2048, sampler=valid_idx, collate_fn=DS.cfn)
test_dl = DataLoader(DS, batch_size=2048, sampler=valid_idx, collate_fn=DS.cfn)

model = DNNCVAE(DS.num_ligand_feat, 16, DS.num_target_feat + DS.num_metal_feat,
                encoder_hidden_dim=128, encoder_hidden_layers=4,
                decoder_hidden_dim=128, decoder_hidden_layers=4)

tr = VAETrainer(model, 1e-5)

path = '/home/jhyang/WORKSPACES/MODELS/isyn/VAE/dnn_16_cgcnn_test'
os.makedirs(path, exist_ok=True)
writer = SummaryWriter(path)
for i in range(50):
    train_loss = tr.train(train_dl)
    writer.add_scalar('Loss/Train', train_loss, i+1)
    valid_loss, valid_output = tr.test(valid_dl)
    test_loss, test_output = tr.test(test_dl)

    writer.add_scalar('Loss/Valid', valid_loss, i+1)
    writer.add_scalar('Loss/Test', test_loss, i+1)
    writer.add_scalar('KLD/Valid', valid_output['kld'], i+1)
    writer.add_scalar('KLD/Test', test_output['kld'], i+1)


In [4]:
from src.feature import feature_to_composit, ligand_label
def feature_to_ligand_index(feat_vec, tol=0.5):
    comps = feature_to_composit(feat_vec, tol)
    out = []
    for comp in comps:
        eles = '-'.join(comp.keys())
        i = ligand_label.get(eles)
        out.append(-1 if i is None else i)
    return out

inp = feature_to_ligand_index(valid_output['input'])
prd = feature_to_ligand_index(valid_output['pred'])

In [11]:
from sklearn.metrics import confusion_matrix


array([[   0,    0,    0, ...,    0,    0,    0],
       [   0, 8313,  120, ...,    0,    0,    0],
       [   0,  230, 2259, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0]])

In [52]:

def _feature_to_composit(feat_vec, tol=0.5, to_string=False, to_idx=False):
    n_feat = feat_vec.shape[-1]
    if n_feat not in [97, 87, 12]:
        raise TypeError(f'feature type is not supported', composit_fnc)
    if n_feat == 97: # active_composit
        ref = ActiveElements
    elif n_feat == 87: # metal_composit
        ref = ['None'] + MetalElements
    elif n_feat == 12: # ligand_composit
        ref = ['Metal'] + LigandElements
    mask = feat_vec > tol
    out = [tuple([ref[i] for i in np.where(vec)[0]]) for vec in mask]
    if to_string or to_idx:
        out = ['-'.join(o) for o in out]
    if to_idx:
        out = [ligand_label[o] if o in ligand_label.keys() else -1 for o in out]
    return out


In [70]:
from sklearn.metrics import f1_score

f1_score(inp, prd, average='micro')

0.9063270336894002

In [72]:
'.'.join(ligand_label.keys())

'Metal-O.Metal-C-O.Metal.Metal-H-O.Metal-N-O.Se.H-N-O-P.S.Metal-H-C-O.Metal-F.Metal-S.Metal-N.Metal-Cl.Metal-H-N-O.Metal-O-P.Metal-H-O-P.P.Metal-Se.C.O-P.Metal-I.Metal-O-S.H-O-P.Metal-Br.Metal-C.Metal-H.H-C-O.H-N-Cl.P-S.Metal-H-N.P-Se.Metal-P.H-N-F.Metal-O-Cl.O-Se.I.H-N-O-S.Metal-C-N.H-O-S.Metal-H-N-O-P.H-N-Br.H-C-S-I.Metal-O-Br.H-C-S-Cl.H-C-S-Br.Metal-C-S.Metal-O-Se.Metal-H-N-Cl.Metal-P-S-Se.H-C-N-S.Metal-O-F-P.N-P.Cl.Metal-P-S.Metal-H-N-O-S.H-Cl.Metal-H-O-S.H-C.Metal-H-C-N-O-P.H-C-N-O.Metal-H-F.Br.Metal-O-F.H-N-O.H-O-Se.Metal-H-Cl.H-S.C-N-S.Metal-O-I.H-C-N.Metal-O-P-Cl.Metal-H-O-Cl.Metal-P-S-Br.H-C-N-Cl.Metal-H-C-N-Cl.H-C-N-I.Metal-H-C-N-I.Metal-H-C-N-Br.Metal-S-Se'

In [18]:
import numpy as np
import matplotlib.pyplot as plt

def cyclical_kld_annealing(epochs, start=0, stop=1, n_cycle=4, ratio=0.5):
    '''
    Code from paper 'Cyclical Annealing Schedule: A Simple Approach to Mitigating KL Vanishing'
    arXiv: https://arxiv.org/abs/1903.10145
    github: https://github.com/haofuml/cyclical_annealing

    Scheduling KLD for better training of VAE.
    '''
    beta = np.ones(epochs)
    period = epochs / n_cycle
    step = (stop - start) / (period * ratio)
    for c in range(n_cycle):
        v, i = start, 0
        while v <= stop and (int(i+c*period) < epochs):
            beta[int(i+c*period)] = v
            v += step
            i += 1
    return beta

def fnc(epochs, start=0, stop=1, n_cycle=4, ratio=0.5):
    beta = np.ones(epochs)
    period = epochs / n_cycle
    step = (stop - start) / (period * ratio)
    for i in range(int(period)):
        beta[i::int(period)] = start + step * i
    return np.clip(beta, start, stop)

epochs = 50000
%timeit fnc(epochs)
%timeit cyclical_kld_annealing(epochs)
#f, axs = plt.subplots(3,1, figsize=(10,8), sharex=True)
#axs[0].scatter(range(epochs), y1)
#axs[1].scatter(range(epochs), y2)
#axs[2].scatter(range(epochs), (np.abs(y1 - y2) > 1e-15).astype(float))


2.98 ms ± 20.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.9 ms ± 26.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
import sys
sys.path.append('..')
from src.data import ReactionDataset
from src.feature import init_info

init_info(0)
rd = ReactionDataset(precursor_feat_type='active_composit')
rd.from_file()
len(rd)

31387

In [3]:
rd.to('cpu')
feat, info = rd.cfn(rd)

In [4]:
import numpy as np
np.unique(feat['label'].numpy(), return_counts=True)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

# -