In [86]:
import sys, os, json, pickle, gzip, copy, torch, numbers, tqdm
sys.path.append('..')
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from itertools import product

from src.utils import ActiveElements, MetalElements, Element, AllElements
from src.utils import composit_parser, linear_kld_annealing, get_is_last, compute_acc, compute_top_accuracy
from src.utils import heat_tempearture_norm, heat_tempearture_denorm, heat_time_norm, heat_time_denorm
from src.utils import parse_sampling_output, get_likely_list
from src.feature import composition_to_feature
from src.trainer import VAETrainer, BaseTrainer
from src.data import ReactionGraphDataset
from src.networks import GraphCVAE

from pymatgen.core import Composition, Element

from scipy.stats import gaussian_kde
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, precision_score, recall_score

from torch.utils.data import DataLoader
torch.set_float32_matmul_precision('high')

In [2]:
with open('../data/info_target_distribution.pkl','rb') as f:
    target_network = pickle.load(f)

def get_origin(id):
    i = target_network[id]
    if isinstance(i, int):
        return get_origin(i)
    else:
        return i

with gzip.open('../data/screened_precursor.pkl.gz','rb') as f:
    unique_precursor = pickle.load(f)
pstrs = [p['precursor_str'] for p in unique_precursor]
    
with gzip.open('../data/unique_reaction_ss.pkl.gz','rb') as f:
    unique_reaction = pickle.load(f)
rxn_id_to_idx = {d['id_reaction']:i for i, d in enumerate(unique_reaction)}
rxn_idx_to_id = [d['id_reaction'] for d in unique_reaction]

with open('/home/jhyang/WORKSPACES/DATA/ICSD_articles/parsed_lv2.pkl','rb') as f:
    icsd_data = pickle.load(f)

# test data analysis

In [112]:
valid_data = []
for i, d in enumerate(icsd_data):
    skip = False
    metals = []
    target_metals = [e for e in d['target_comp'].keys() if e in MetalElements]
    for p in d['precursor_comp']:
        pstr = composit_parser(p)
        if pstr not in pstrs:
#            print(i, d['doi'], pstr)
            skip = True
            break
        p_metals = [e for e in p.keys() if e in MetalElements]
        if len(p_metals) == 0:
            metal = 'none'
        elif len(p_metals) == 1:
            metal = p_metals[0]
        else:
            skip = True
            break

        if (metal in metals) or (metal not in target_metals):
            skip = True
            break
        else:
            metals.append(metal)

    if not skip:
        valid_data.append({
            'doi': d['doi'],
            'target_comp': {e:n/np.sum(list(d['target_comp'].values())) for e,n in d['target_comp'].items()},
            'precursor_comp': [{e:n/np.sum(list(p.values())) for e,n in p.items()} for p in d['precursor_comp']],
            'precursor_comp_': d['precursor_comp'],
            'heat_time': d['heat_time'],
            'heat_temp': d['heat_temp'],
        })
print(len(valid_data), ' / ', len(icsd_data))

257  /  427


In [246]:
icsd_target_vector = np.vstack([composition_to_feature(d['target_comp'], feature_type='composit') for d in valid_data])
unique_target_vector = np.vstack([composition_to_feature(r['target_comp'], feature_type='composit') for r in unique_reaction])

dist = np.square(unique_target_vector[:, np.newaxis, :] - icsd_target_vector).sum(-1).T
similar_target_mask = dist < 1e-8
similar_target_idxs_icsd, similar_target_idxs_urxn = np.where(similar_target_mask)

In [114]:
np.unique(similar_target_idxs_icsd)

array([  0,  17,  55,  56,  57,  58,  61,  66,  67,  73,  85, 121, 122,
       123, 125, 126, 127, 129, 130, 131, 144, 146, 161, 167, 170, 174,
       183, 185, 188, 201, 209, 219, 228, 233, 234, 235, 236, 237, 238,
       244, 250, 252, 253, 256])

### unique but similar target

In [115]:
mask_new_target = np.sum(dist < 1e-8, 1) == 0
for i in range(mask_new_target.sum()):
    d = dist[mask_new_target][i].min()
    if d > 1e-5:
        continue
    j = dist[mask_new_target][i].argmin()
    k = np.where(mask_new_target)[0][i]
    print(f'{k:4d} / {j:6d} / {d:.12f}')

    for k,v in valid_data[k].items():
        print(f'{k}: {v},')
    print('-'*100)
    for key in ['target_comp','precursor_comp','heat_time_med','heat_temp_med']:
        print(f'{key}: {unique_reaction[j][key]},')
    print('='*100)
    print('='*100)


 231 /  24849 / 0.000008425943
doi: 10.1021/acs.inorgchem.1c00319,
target_comp: {'Na': 0.24717691342534504, 'Mg': 0.12358845671267252, 'Si': 0.1273525721455458, 'O': 0.5018820577164367},
precursor_comp: [{'Na': 0.3333333333333333, 'C': 0.16666666666666666, 'O': 0.5}, {'Mg': 0.5, 'O': 0.5}, {'Si': 0.3333333333333333, 'O': 0.6666666666666666}],
precursor_comp_: [{'Na': 2.0, 'C': 1.0, 'O': 3.0}, {'Mg': 1.0, 'O': 1.0}, {'Si': 1.0, 'O': 2.0}],
heat_time: [36.0],
heat_temp: [1248.15],
----------------------------------------------------------------------------------------------------
target_comp: {'Na': 0.24623115, 'Mg': 0.12562814, 'Si': 0.12562814, 'O': 0.5025126},
precursor_comp: [{'Na': 0.33333334, 'C': 0.16666667, 'O': 0.5}, {'Mg': 0.5, 'O': 0.5}, {'Si': 0.33333334, 'O': 0.6666667}],
heat_time_med: 2.0,
heat_temp_med: 1223.15,
 245 /   1496 / 0.000000080001
doi: 10.1016/j.jallcom.2022.166081,
target_comp: {'Sr': 0.2, 'Hf': 0.1998, 'Er': 0.0002, 'O': 0.6},
precursor_comp: [{'Sr': 0.2, 'C

In [117]:
a = {'Na': 0.24717691342534504, 'Mg': 0.12358845671267252, 'Si': 0.1273525721455458, 'O': 0.5018820577164367}
b = {'Na': 0.24623115, 'Mg': 0.12562814, 'Si': 0.12562814, 'O': 0.5025126}
d1 = 0.5018820577164367  * 0.125
d2 = 0.50251255 * 0.125
for e in a.keys():
    print(f'{e:3s} {a[e]/d1:12.8f} {b[e]/d2:12.8f}')

Na    3.94000000   3.92000001
Mg    1.97000000   2.00000004
Si    2.03000000   2.00000004
O     8.00000000   8.00000080


- 동일하진 않으나, doping 농도에서 약간의 차이를 보이는 샘플들이 있음.

### similar target #1 (element)

In [12]:
i = 0
for k, v in valid_data[i].items():
    print(f'{k}: {v},')
print()
j = rxn_idx_to_id[same_target_idxs_urxn[same_target_idxs_icsd == i][0]]
net_data = get_origin(j)
for j, d in zip(net_data['id_reaction'], net_data['dist']):
    k = rxn_id_to_idx[j]
    if d > 1e-9: continue
    print(f'{k:4d} : {d:.6f}')
    for key in ['target_comp','precursor_comp','heat_time_med','heat_temp_med']:
        print(f'{key}: {unique_reaction[k][key]},')
    print('-'*100)

doi: 10.1021/jacs.2c09863,
target_comp: {'Li': 0.4444444444444444, 'Si': 0.1111111111111111, 'O': 0.4444444444444444},
precursor_comp: [{'Li': 0.3333333333333333, 'C': 0.16666666666666666, 'O': 0.5}, {'Si': 0.3333333333333333, 'O': 0.6666666666666666}],
precursor_comp_: [{'Li': 2.0, 'C': 1.0, 'O': 3.0}, {'Si': 1.0, 'O': 2.0}],
heat_time: [12.0],
heat_temp: [1073.0],

 928 : 0.000000
target_comp: {'Li': 0.44444445, 'Si': 0.11111111, 'O': 0.44444445},
precursor_comp: [{'Si': 0.33333334, 'O': 0.6666667}, {'Li': 0.33333334, 'C': 0.16666667, 'O': 0.5}],
heat_time_med: 4.5,
heat_temp_med: 1073.15,
----------------------------------------------------------------------------------------------------
 929 : 0.000000
target_comp: {'Li': 0.44444445, 'Si': 0.11111111, 'O': 0.44444445},
precursor_comp: [{'Si': 0.16666667, 'H': 0.33333334, 'O': 0.5}, {'Li': 0.33333334, 'C': 0.16666667, 'O': 0.5}],
heat_time_med: 6.0,
heat_temp_med: 1098.15,
------------------------------------------------------------

### similar target #2 (fraction)

In [122]:
i = 256
for k, v in valid_data[i].items():
    print(f'{k}: {v},')
print()

js = np.argsort(dist[i])[:5]
for j, d in zip(js, dist[i, js]):
    print(f'{j:4d} : {d:.6f}')
    for key in ['target_comp','precursor_comp','heat_time_med','heat_temp_med']:
        print(f'{key}: {unique_reaction[j][key]},')
    print('-'*100)

doi: 10.1021/acs.inorgchem.2c03332,
target_comp: {'Tb': 0.1, 'Ba': 0.1, 'Co': 0.2, 'O': 0.6},
precursor_comp: [{'Tb': 0.4, 'O': 0.6}, {'Ba': 0.2, 'C': 0.2, 'O': 0.6}, {'Co': 0.4, 'O': 0.6}],
precursor_comp_: [{'Tb': 2.0, 'O': 3.0}, {'Ba': 1.0, 'C': 1.0, 'O': 3.0}, {'Co': 2.0, 'O': 3.0}],
heat_time: [12.0],
heat_temp: [1473.15],

10373 : 0.000000
target_comp: {'Ba': 0.1, 'Tb': 0.1, 'Co': 0.2, 'O': 0.6},
precursor_comp: [{'Co': 0.42857143, 'O': 0.5714286}, {'Ba': 0.2, 'C': 0.2, 'O': 0.6}, {'Tb': 0.36363637, 'O': 0.6363636}],
heat_time_med: None,
heat_temp_med: 1473.15,
----------------------------------------------------------------------------------------------------
6897 : 0.002716
target_comp: {'Ba': 0.11111111, 'Tb': 0.11111111, 'Co': 0.22222222, 'O': 0.5555556},
precursor_comp: [{'Co': 0.42857143, 'O': 0.5714286}, {'Ba': 0.2, 'C': 0.2, 'O': 0.6}, {'Tb': 0.36363637, 'O': 0.6363636}],
heat_time_med: None,
heat_temp_med: 1273.15,
--------------------------------------------------------

### similar target #3 (exact composition)

In [123]:
i = 256
for k, v in valid_data[i].items():
    print(f'{k}: {v},')
print()

eles = list(valid_data[i]['target_comp'].keys())

js = [j for j, rxn in enumerate(unique_reaction) if all([x in rxn['target_comp'].keys() for x in eles]) and (len(rxn['target_comp']) == len(eles))]
js = sorted(js, key=lambda x: dist[i, x])
for j in js:
    print(f'{j:4d} : {dist[i,j]:.6f}')
    for key in ['target_comp','precursor_comp','heat_time_med','heat_temp_med']:
        print(f'{key}: {unique_reaction[j][key]},')
    print('-'*100)

doi: 10.1021/acs.inorgchem.2c03332,
target_comp: {'Tb': 0.1, 'Ba': 0.1, 'Co': 0.2, 'O': 0.6},
precursor_comp: [{'Tb': 0.4, 'O': 0.6}, {'Ba': 0.2, 'C': 0.2, 'O': 0.6}, {'Co': 0.4, 'O': 0.6}],
precursor_comp_: [{'Tb': 2.0, 'O': 3.0}, {'Ba': 1.0, 'C': 1.0, 'O': 3.0}, {'Co': 2.0, 'O': 3.0}],
heat_time: [12.0],
heat_temp: [1473.15],

10373 : 0.000000
target_comp: {'Ba': 0.1, 'Tb': 0.1, 'Co': 0.2, 'O': 0.6},
precursor_comp: [{'Co': 0.42857143, 'O': 0.5714286}, {'Ba': 0.2, 'C': 0.2, 'O': 0.6}, {'Tb': 0.36363637, 'O': 0.6363636}],
heat_time_med: None,
heat_temp_med: 1473.15,
----------------------------------------------------------------------------------------------------
6897 : 0.002716
target_comp: {'Ba': 0.11111111, 'Tb': 0.11111111, 'Co': 0.22222222, 'O': 0.5555556},
precursor_comp: [{'Co': 0.42857143, 'O': 0.5714286}, {'Ba': 0.2, 'C': 0.2, 'O': 0.6}, {'Tb': 0.36363637, 'O': 0.6363636}],
heat_time_med: None,
heat_temp_med: 1273.15,
--------------------------------------------------------

# Evaluation

## load models

In [176]:
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

model_desc = 'cgcnn+elemnet_convolution_m04.128.8_batch_0064'
model_root = '/home/jhyang/WORKSPACES/MODELS/isyn/GCVAE_CASE_1_condition'

models = []
ths = []
for i in range(5):
    path = os.path.join(model_root, model_desc, f'cv_{i:02d}')
    models.append(
        GraphCVAE(1,1,1,1).load(path, prefix='best', requires_grad=False)
    )
    tbevent_fn = [fn for fn in os.listdir(path) if fn.startswith('events')][0]
    ea = EventAccumulator(os.path.join(path, tbevent_fn))
    th = [th for th in ea.Reload().Scalars('Hit/Th') if th.step == ea.Reload().Scalars('Loss/BestValid')[-1].step][0].value
    ths.append(th)

def get_sampling_output(model, feat_type, target_comp, heat_temp, heat_time, 
                        n_sample=1000, device='cuda'):
    RGDS = ReactionGraphDataset(feat_type = feat_type, base_info_attrs = [])
    new_data = [{'target_comp':target_comp, 'heat_temp':t1, 'heat_time':t2} for t1, t2 in product(heat_temp, heat_time)]
    RGDS.from_dataset(new_data, heat_temp_fnc=lambda x: x['heat_temp'], heat_time_fnc=lambda x: x['heat_time'], extend_dataset=False)
    dataloader = DataLoader(RGDS, batch_size=2048, collate_fn=RGDS.cfn)
    tr = VAETrainer(model, 1, device=device)
    sampling_output = tr.sampling(dataloader, n_sample=n_sample)
    return sampling_output
#    tr = VAETrainer(model=model, lr=0)
#    return tr.sampling(dataloader, n_sample=n_sample)


## test

In [125]:
ds = ReactionGraphDataset('cgcnn+elemnet')
ds.from_dataset(valid_data,
                heat_temp_fnc=lambda x: np.mean(x['heat_temp']),
                heat_time_fnc=lambda x: np.mean(x['heat_time']))

outputs_sampling = []
outputs_test = []
for model in models:
    tr = VAETrainer(model, 1, device='cuda')
    output =tr.sampling(DataLoader(ds, batch_size=2048, collate_fn=ds.cfn), 100)
    outputs_sampling.append(output)
    _, output =tr.test(DataLoader(ds, batch_size=2048, collate_fn=ds.cfn))
    outputs_test.append(output)


In [84]:
#parse_sampling_output(outputs_sampling[0], ds.precursor_dataset)

In [145]:
#pred_label.argmax(1), label.argmax(1)
outputs_test[fold_idx].keys()

dict_keys(['info', 'label', 'weight', 'rxn_id', 'pred_has', 'pred_label', 'kld', 'mu', 'log_var', 'z'])

In [238]:
meta = outputs_test[fold_idx]['info'][sample_idx]
target = meta['target_comp']
metals = meta['metals']
heat_temps = meta['heat_temp']
heat_times = meta['heat_time']
    
cv_output_metric = []
for fold_idx in range(5):
    _out = {j:[] for j in np.unique(outputs_test[fold_idx]['rxn_id']).astype(int)}
    rxn_id = outputs_test[fold_idx]['rxn_id']
    is_last = get_is_last(rxn_id)
    label = outputs_test[fold_idx]['label']
    pred_label = outputs_test[fold_idx]['pred_label']
    pred_has_ = outputs_test[fold_idx]['pred_has']
    pred_has = pred_has_ > ths[fold_idx]
    for i, l, pl, ph, il in zip(rxn_id, label, pred_label, pred_has, is_last):
        if il:
            continue
        m_p = np.where(pl > 0)[0]
        p_order = m_p[np.argsort(pl[m_p])][::-1].tolist()
        j = p_order.index(l.argmax())
        _out[i].append(j)
    cv_output_metric.append(_out)

In [242]:
[np.where(outputs_test[i]['pred_has'][is_last] > ths[i]) for i in range(5)]

[(array([ 55, 213, 214]),),
 (array([ 55, 213, 214]),),
 (array([ 55, 172, 213, 214]),),
 (array([ 55, 213, 214]),),
 (array([191, 213, 214]),)]

In [254]:
dist.min(1)

array([0.00000000e+00, 5.05879638e-04, 2.52171373e-03, 1.26956124e-02,
       1.24999201e-02, 1.26956124e-02, 1.18339350e-02, 9.79311857e-03,
       8.88608862e-03, 8.34187120e-03, 1.64346434e-02, 6.12052623e-04,
       4.74612374e-04, 5.51477773e-04, 5.28571021e-04, 1.84356933e-03,
       5.63214591e-04, 0.00000000e+00, 1.45471431e-02, 1.52879702e-02,
       1.65180024e-02, 1.82529595e-02, 6.58420660e-03, 5.41666662e-03,
       4.66907490e-03, 4.67264652e-03, 1.43561214e-02, 1.49346925e-02,
       1.27999997e-02, 9.80000012e-03, 1.38775492e-02, 2.52049193e-02,
       2.77606808e-02, 3.40185203e-02, 1.46157778e-04, 1.44756035e-04,
       1.50165171e-04, 1.62300668e-04, 1.51618893e-04, 1.43332029e-04,
       1.51618893e-04, 1.48441351e-04, 8.78379738e-04, 1.04401901e-03,
       1.81643572e-03, 2.75220838e-03, 4.50717751e-03, 1.36000011e-02,
       1.36888912e-02, 1.33555569e-02, 1.34222247e-02, 1.38888899e-02,
       1.47555573e-02, 1.34000015e-02, 5.41230515e-02, 0.00000000e+00,
      

In [218]:
is_last = get_is_last(outputs_test[i]['rxn_id'])
last_l = outputs_test[i]['label'][is_last]
last_pl = outputs_test[i]['pred_label'][is_last]
last_ph_ = outputs_test[i]['pred_has'][is_last]
last_ph = last_ph_ > ths[i]
[valid_data[j] for j in np.where(last_ph)[0]]

[{'doi': '10.1021/acs.chemmater.0c03978',
  'target_comp': {'Na': 0.18181818182561982,
   'Mn': 0.2181818181798347,
   'Zn': 0.027272727272479338,
   'Ti': 0.027272727272479338,
   'O': 0.5454545454495867},
  'precursor_comp': [{'Na': 0.3333333333333333,
    'C': 0.16666666666666666,
    'O': 0.5},
   {'Mn': 0.4, 'O': 0.6},
   {'Zn': 0.5, 'O': 0.5},
   {'Ti': 0.3333333333333333, 'O': 0.6666666666666666}],
  'precursor_comp_': [{'Na': 2.0, 'C': 1.0, 'O': 3.0},
   {'Mn': 2.0, 'O': 3.0},
   {'Zn': 1.0, 'O': 1.0},
   {'Ti': 1.0, 'O': 2.0}],
  'heat_time': [12.0],
  'heat_temp': [1273.15]},
 {'doi': '10.1021/acs.chemmater.1c04374',
  'target_comp': {'Na': 0.3333333333333333,
   'Ti': 0.16666666666666666,
   'S': 0.5},
  'precursor_comp': [{'Ti': 0.3333333333333333, 'S': 0.6666666666666666},
   {'Na': 0.6666666666666666, 'S': 0.3333333333333333}],
  'precursor_comp_': [{'Ti': 1.0, 'S': 2.0}, {'Na': 2.0, 'S': 1.0}],
  'heat_time': [48.0],
  'heat_temp': [773.0]},
 {'doi': '10.1021/acs.chemmat

0

In [227]:
p_order.index

[4, 51, 32, 19, 5, 18, 54, 7, 41, 64, 24, 57, 44, 28, 115, 36, 78, 126]